### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by blu94** [NimaSaed/G10B_Sales_of_Point_System_for_Video_and_Audio_shop#1]
Current Version of ER diagram
Please have a look and give comment.
![erd](https://cloud.githubusercontent.com/assets/16028996/12215642/1bee8256-b701-11e5-947f-79da9acbaf73.PNG)

**Comment by NimaSaed** [comment]
Seems like you have so many unnecessary tables, please list your conditions here, so I can give you comment.

**Comment by blu94** [comment]
1- A Video/Audio shop is a shop where items like VCD, Audio CD, Music Tape
and Video Cassette are sold or given for rent.
2- System, therefore, should have two main parts, Sales and Rent
3- In each part, system should be able to show a list of available items
for sale or rent.
4- Each item should have properties like title, serial number, price and
quantity.
5- A customer either can buy an item or rent it. In either cases an item
should be selected and removed from available list and added to Rented list
or Sold list
6- System should be able to record information about each sale or rent.
7- A customer can buy as many items as he/she wants, but only five items
can be rented by an individual customer at a time.
8- Only subscribed customers are able to rent an item. Each subscriber has
a customer ID and password.
9- After finishing buying or renting the items, a report (or receipt) must
be generated and shown to the customer. Reports should contain the items,
their prices the total value and other necessary details for purchase or
rent.

2016-01-10 10:43 GMT+08:00 Nima Saed notifications@github.com:

**Comment by blu94** [comment]
Dear Nima,
Do you mean we just have to build a small system and we have to remove or merge some table?
or when do you free for this week? i go to your office and discuss about the ERD?

**Comment by NimaSaed** [comment]
Let me read this carefully, I will come back to you soon.

**Comment by blu94** [comment]
This is a new ERD, Pls have a look and comment.
![erd](https://cloud.githubusercontent.com/assets/16028996/12344447/22c04274-bb78-11e5-9bc8-a046a313f130.PNG)

If got any improvement or any comment pls tell me faster, my editor left 2 day to edit, after that have to purchase ady. TQTQ.

**Comment by NimaSaed** [comment]
Admin can be in user table but with admin privileges (one column defines group member), normal user group has normal privilege. You can have rented table and sold table, because information for rent and sell is different. shipping cost is different depending to user address so don't put it as fix value in product table, you can calculate the shipment during check out.

**Comment by blu94** [comment]
![erd](https://cloud.githubusercontent.com/assets/16028996/12372621/c65eb330-bc99-11e5-9d49-59faf40f50d5.PNG)
pls check,TQ

**Comment by NimaSaed** [comment]
what is manage?

**Comment by blu94** [comment]
at first manage is for admin to add item to product, although now admin and user merge together, but i think it is still important for our system.

**Comment by NimaSaed** [comment]
Is it you mean cart or card? if it is card, how about I wanna checkout with more than one movie? seems like you can have only one product ID in card table! (Card and product relationship is many-to-many)

**Comment by blu94** [comment]
yaya, i mean cart, for the add to cart function, like we insert many cart with different product and same user_id, so when we check the cart, we can use the user_id (select \* from cart where user_id = "bla") to find out the product that user added.
